# Generated by Django 4.1.1 on 2023-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='wallet',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Mercury', 'Mercury')], max_length=50, null=True, verbose_name='Customer wallet address Usdt(Trc20)'),
        ),
    ]
