# Generated by Django 4.1.1 on 2023-04-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_withdraw_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='name',
            field=models.CharField(default='Niima', max_length=50, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='name',
            field=models.CharField(default='Niima', max_length=50, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='wallet',
            field=models.CharField(default=23, max_length=50, verbose_name='Customer wallet address Usdt(Trc20)'),
            preserve_default=False,
        ),
    ]
