# Generated by Django 4.1.1 on 2023-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_buy_name_withdraw_name_alter_withdraw_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Full name')),
                ('body', models.TextField(verbose_name='Message')),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
